version: "3.9"

services:
  web:
    image: custom-nginx-php:latest # Custom image with Nginx and PHP-FPM
    ports:
      - "80:80" # Expose port 80
    deploy:
      placement:
        constraints:
          - node.hostname == ip-172-31-17-225 # Worker Node 1
      replicas: 1
    networks:
      - app-network
    volumes:
      - ./html:/var/www/html # Application files
      - ./nginx.conf:/etc/nginx/conf.d/default.conf # Custom Nginx config
    depends_on:
      - db
 
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: app_db
      MYSQL_USER: root
      MYSQL_PASSWORD: DemoPass
    deploy:
      placement:
        constraints:
          - node.hostname == ip-172-31-16-165 # Worker Node 2  http://172.31.16.165/
      replicas: 1
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: overlay

volumes:
  db-data:
