version: "3.9"

services:
  php-fpm:
    image: php:8.3-fpm
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == worker
    volumes:
      - .:/var/www/html
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - php-fpm
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    volumes:
      - db-data:/var/lib/mysql
    deploy:
      placement:
        constraints:
          - node.hostname == <Dator-3-Hostname>
    networks:
      - app-network

networks:
  app-network:

volumes:
  db-data:
